build rename_script

diff --git a/scripts/new_script b/scripts/new_script
--- a/scripts/new_script
+++ b/scripts/new_script
@@ -1,78 +1,78 @@
 #!/bin/zsh
 
 show_usage() {
-    echo "┌───────────────────┐"
-    echo "| new_script <name> |"
-    echo "└───────────────────┘"
+  echo "┌───────────────────┐"
+  echo "| new_script <name> |"
+  echo "└───────────────────┘"
 }
 
 if [[ "$1" == "-h" || "$1" == "--help" ]]; then
-    show_usage
-    exit 0
+  show_usage
+  exit 0
 fi
 
 if [[ -z "$1" ]]; then
-    echo "No file name provided"
-    exit 1
+  echo "No file name provided"
+  exit 1
 fi
 
 expand_tilde() {
-    echo "$1" | sed "s|^~$|${HOME}|g; s|^~|${HOME}|g"
+  echo "$1" | sed "s|^~$|${HOME}|g; s|^~|${HOME}|g"
 }
 
 SCRIPT_DIR=$(expand_tilde "~/dotfiles/scripts")
 BIN_DIR=$(expand_tilde "~/bin")
-TARGET_SCRIPT="$SCRIPT_DIR/$1"
-SYMLINK_TARGET="$BIN_DIR/$1"
+TARGET_SCRIPT="${SCRIPT_DIR}/$1"
+SYMLINK_TARGET="${BIN_DIR}/$1"
 
-command -v "$1" > /dev/null 2>&1
+command -v "$1" >/dev/null 2>&1
 if [ $? -eq 0 ]; then
   echo "\`$1\` already exists. Try another name."
   exit 1
 fi
 
-mkdir -p "$SCRIPT_DIR"
+mkdir -p "${SCRIPT_DIR}"
 
-if [[ -e "$TARGET_SCRIPT" ]]; then
-    echo "Script file '$TARGET_SCRIPT' already exists."
-    exit 1
+if [[ -e "${TARGET_SCRIPT}" ]]; then
+  echo "Script file '${TARGET_SCRIPT}' already exists."
+  exit 1
 fi
 
-if [[ -e "$SYMLINK_TARGET" ]]; then
-    echo "Symbolic link '$SYMLINK_TARGET' already exists."
-    exit 1
+if [[ -e "${SYMLINK_TARGET}" ]]; then
+  echo "Symbolic link '${SYMLINK_TARGET}' already exists."
+  exit 1
 fi
 
-if [ -f "$SCRIPT_DIR/boilerplate" ]; then
-    cat "$SCRIPT_DIR/boilerplate" > "$TARGET_SCRIPT"
+if [ -f "${SCRIPT_DIR}/boilerplate" ]; then
+  cat "${SCRIPT_DIR}/boilerplate" >"${TARGET_SCRIPT}"
 else
-    touch "$TARGET_SCRIPT"
-    echo "Boilerplate file not found. Created empty script."
+  touch "${TARGET_SCRIPT}"
+  echo "Boilerplate file not found. Created empty script."
 fi
 
-chmod +x "$TARGET_SCRIPT"
+chmod +x "${TARGET_SCRIPT}"
 
-ln -s "$TARGET_SCRIPT" "$SYMLINK_TARGET"
+ln -s "${TARGET_SCRIPT}" "${SYMLINK_TARGET}"
 
-echo "Created new script: $TARGET_SCRIPT"
+echo "Created new script: ${TARGET_SCRIPT}"
 echo "Linked to: $SYMLINK_TARGET"
 
-echo "Open $TARGET_SCRIPT? (y/n)"
-read -r response
-if [[ "$response" == "y" || "$response" == "Y" ]]; then
-    echo "[1] Open with zopen"
-    echo "[2] Open with Vim"
-    echo "[3] Open with Zed"
-    read buffer_type
-    if [[ "$buffer_type" == "1" ]]; then
-        zopen "$TARGET_SCRIPT"
-    elif [[ "$buffer_type" == "2" ]]; then
-        vim "$TARGET_SCRIPT"
-    elif [[ "$buffer_type" == "3" ]]; then
-        zed "$TARGET_SCRIPT"
-    else
-        echo "Invalid choice."
-    fi
+echo "Open ${TARGET_SCRIPT}? (y/n)"
+read response
+if [[ "${response}" == "y" || "${response}" == "Y" ]]; then
+  echo "[1] Open with zopen"
+  echo "[2] Open with Vim"
+  echo "[3] Open with Zed"
+  read buffer_type
+  if [[ "${buffer_type}" == "1" ]]; then
+    zopen "${TARGET_SCRIPT}"
+  elif [[ "${buffer_type}" == "2" ]]; then
+    vim "${TARGET_SCRIPT}"
+  elif [[ "${buffer_type}" == "3" ]]; then
+    zed "${TARGET_SCRIPT}"
+  else
+    echo "Invalid choice."
+  fi
 fi
 
 exit 0
diff --git a/scripts/rename_script b/scripts/rename_script
--- a/scripts/rename_script
+++ b/scripts/rename_script
@@ -1,6 +1,9 @@
 #!/bin/bash
 # Description of this script
 
+readonly BIN_DIR="${HOME}/bin"
+readonly SCRIPTS_DIR="${HOME}/dotfiles/scripts"
+
 show_usage() {
   echo "┌─┐"
   echo "| \$ |"
@@ -9,35 +12,56 @@ show_usage() {
 
 main() {
 
-    # printf "\e[1;31mLight Red Text\e[0m\n"
-    # printf "\e[1;32mLight Green Text\e[0m\n"
-    # printf "\e[1;33mYellow Text\e[0m\n"
-    # printf "\e[1;34mLight Blue Text\e[0m\n"
-    # printf "\e[1;35mLight Purple Text\e[0m\n"
-    # printf "\e[1;36mLight Cyan Text\e[0m\n"
-    # printf "\e[1;37mWhite Text\e[0m\n"
-  # if [[ "$1" == "-h" || "$1" == "--help" ]]; then
-  #   show_usage
-  #   exit 0
-  # fi
+  if [[ "$1" == "-h" || "$1" == "--help" ]]; then
+    show_usage
+    exit 0
+  fi
 
-  # if [[ -z "$1" ]]; then
-  #   echo "No argument provided"
-  #   show_usage
-  #   exit 1
-  # fi
+  if [[ -z "$1" ]]; then
+    echo "Existing script name not provided"
+    show_usage
+    exit 1
+  fi
+
+  if [[ -z "$2" ]]; then
+    echo "New script name not provided"
+    show_usage
+    exit 1
+  fi
+
+  local existing_script_name="$1"
+  local symlink="${BIN_DIR}/${existing_script_name}"
+  local readlink_result
+  readlink_result=$(readlink "${symlink}")
+  if [[ "${readlink_result}" != "${SCRIPTS_DIR}/${existing_script_name}" ]]; then
+    echo "Symbolic link does not exist at ${symlink}"
+    echo "Exiting . . ."
+    exit 1
+  fi
+
+  local new_script_name="$2"
+  command -v "${new_script_name}" >/dev/null 2>&1
+  if [[ $? -eq 0 ]]; then
+    echo "\`${new_script_name}\` already exists. Try another name."
+    exit 1
+  fi
+
+  local unlink_result
+  unlink_result=$(
+    unlink "${symlink}"
+    echo $?
+  )
+  if [[ "${unlink_result}" -eq 1 ]]; then
+    echo "Failed to unlink ${symlink}"
+  fi
+
+  mv "${SCRIPTS_DIR}/${existing_script_name}" "${SCRIPTS_DIR}/${new_script_name}"
+  ln -s "${SCRIPTS_DIR}/${new_script_name}" "${BIN_DIR}/${new_script_name}"
+
+  echo "New symlink created:"
+  readlink "${BIN_DIR}/${new_script_name}"
 
   exit 0
 }
 
 main "$@"
-
-# kanwoody@Kans-iMac scripts % ln -s ~/dotfiles/scripts/test ~/bin/test
-# kanwoody@Kans-iMac scripts % unlink ~/bin/test
-# kanwoody@Kans-iMac scripts % readlink ~/bin/test; echo $?
-# 1
-# kanwoody@Kans-iMac scripts % mv ~/dotfiles/scripts/{test,renamed}
-# kanwoody@Kans-iMac scripts % ln -s ~/dotfiles/scripts/renamed ~/bin/renamed
-# kanwoody@Kans-iMac scripts % readlink ~/bin/renamed; echo $?
-# /Users/kanwoody/dotfiles/scripts/renamed
-# 0
